apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: notesapp
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: notesapp
 minReplicas: 1
 maxReplicas: 10
 targetCPUUtilizationPercentage: 50