apiVersion: v1
kind: Service
metadata:
  name: notesapp
  labels:
    service: notesapp
spec:
  type: NodePort
  selector:
    app: notesapp  
  ports:
  - port: 5000
    nodePort: 30007
    targetPort: 5000
